modLoader="javafml"
loaderVersion="[43,)"
license="Public Domain"

[[mods]]
modId="dimensions"
version="43.2023.1"
displayName="Dimensions"
credits="EleckFan5935, Minecraft Forge and MCreator Mod Maker made or helped making this open-source mod."
displayURL="https://mcreator.net"
updateJSONURL="raw.githubusercontent.com/WoktopusGaming/dimensions/main/update.json"
authors="EleckFan5935"
description='''
Adds brand new dimensions and blocks to Minecraft
'''

[[dependencies.dimensions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




